volumes:
  caddy_data:

services:
  backend:
    environment:
      - DJANGO_DEBUG=0
      - ORCID_USE_SANDBOX=0
      - FRONTEND_APP_URL=https://cfde-eval.netlify.app
      # - FRONTEND_APP_URL=https://deploy-preview-43--cfde-eval-public.netlify.app/

  caddy:
    image: caddy:2.11
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - django_static:/opt/static/
      - ./services/caddy/:/etc/caddy/
      - caddy_data:/data/
