name: Pipeline on GCP VM

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: icc-eval-core-api-pipeline
  cancel-in-progress: false

jobs:
  pipeline:
    runs-on: [self-hosted, Linux, X64, cfde]

    permissions:
      contents: read

    steps:
      - name: Show runner context
        run: |
          set -euo pipefail
          hostname
          whoami
          docker --version
          docker compose version
