name: Run pipeline

on:
  schedule:
    - cron: "0 0 * * 1"

  workflow_dispatch:

env:
  FORCE_COLOR: true

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Install packages
        run: ./run.sh --install

      - name: Install Playwright
        run: ./run.sh --install-playwright
        working-directory: ./public

      - name: Run pipeline
        run: xvfb-run ./run.sh --gather
        env:
          AUTH_ENTREZ: ${{ secrets.AUTH_ENTREZ }}
          CACHE: ${{ inputs.cache && 'true' || '' }}

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update files
          commit_author: "Bot <>"

      - name: Trigger private repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.AUTH_PRIVATE }}
          repository: nih-cfde/icc-eval-core-private
          event-type: pipeline
