name: Run pipeline

on:
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: ./run.sh --install

      - name: Google auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.AUTH_GOOGLE }}"

      - name: Run pipeline
        run: ./run.sh

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update compiled data"
