name: Run pipeline

on:
  workflow_dispatch:
    inputs:
      cache:
        type: boolean
        description: Use cache
        default: false

  schedule:
    - cron: "0 0 * * 1"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Install packages
        run: ./run.sh --install

      - name: Install Playwright
        uses: ./.github/actions/install-playwright
        with:
          working-directory: ./data

      - name: Google auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.AUTH_GOOGLE }}

      - name: Run pipeline
        run: xvfb-run ./run.sh --gather
        env:
          AUTH_ENTREZ: ${{ secrets.AUTH_ENTREZ }}
          AUTH_GITHUB: ${{ secrets.AUTH_GITHUB }}
          AUTH_GOOGLE: ${{ secrets.AUTH_GOOGLE }}
          CACHE: ${{ inputs.cache && 'true' || '' }}

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update compiled data
          commit_author: "Bot <>"

      # - name: Open pull request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     branch: update-data
      #     title: Update compiled data
