name: Run pipeline

on:
  workflow_dispatch:
    inputs:
      cache:
        type: boolean
        description: Use cache (files in /raw)
        default: false

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Install packages
        run: ./run.sh --install

      - name: Google auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.AUTH_GOOGLE }}

      - name: Run pipeline
        run: |
          touch data/.env.local
          ./run.sh
        env:
          AUTH_GITHUB: ${{ secrets.AUTH_GITHUB }}
          CACHE: ${{ inputs.cache && 'true' || '' }}

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update compiled data
