name: Run tests

on:
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: yarn

      - name: Install /data packages
        run: yarn install
        working-directory: ./data

      - name: Run /data tests
        run: yarn test
        working-directory: ./data

      - name: Install /app packages
        run: yarn install
        working-directory: ./app

      - name: Run /app tests
        run: yarn test
        working-directory: ./app
